name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Andrii Hubenok'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: ' The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'
    value: ${{ steps.cpr.outputs.pull-request-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Run interaction script
      id: generate_code
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/
        if-no-files-found: error

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact

    - name: Display Generated Code using the ls command
      run: ls -R ./autocoder-artifact
      shell: bash

    - name: Configure Credentials and Commit Generated Code
      env:
        GIT_AUTHOR_NAME: autocoder-bot
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_NAME: autocoder-bot
        GIT_COMMITTER_EMAIL: actions@github.com
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add code generated by ChatGPT"
      shell: bash

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        title: "Automated Code for Issue #${{ inputs.ISSUE_NUMBER }}"
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        labels: ${{ inputs.LABEL }}
